### PR TITLE
Update project dependencies

### PR DESCRIPTION
**Pull request by akuzminskyi**
To keep the project in the actual state we need to update some dependencies.

Changes:
- Updated deployment target from `11.0` to `13.0`;
- Updated `Ruby` version from `2.5.3` to `3.1.0`;
- Updated `Xcode` version from `10.2` to `13.2`;
- Updated `Cocoapods` from `1.10.2` to `1.11.2`;
- Updated `Fastlane` from `2.191.0` to `2.199.0`;
- Fixed a Xcode related to `EventObjectInitParam.jet` file, the file was created/marked as `swift`;
- Updated GitHub workflow file:
  - Updated Xcode to `13.2`;
  - Updated some actions;

There are multiple deprecation warnings related to `NSKeyedUnarchiver`, it will be fixed in the next PRs.

### CODE REVIEW

**Review by albertodebortoli — APPROVED** [review]

**Comment by akuzminskyi** [comment]
@albertodebortoli can you please merge it I'm not authorized to merge it.

**Comment by albertodebortoli** [comment]
Would be happy to merge it, but GitHub Actions fails with

```
Using 3.0.3 as input from file .ruby-version
Error: Unknown version 3.0.3 for ruby on macos-11.0
```

**Review by paololeonardi — APPROVED** [review]
LGTM but GitHub Actions is still failing

**Comment by albertodebortoli** [comment]
@paololeonardi yes, we decided to ignore GitHub Actions for now and address it later as it regressed also on other repos.

**Comment by albertodebortoli** [comment]
Using the 4.3.0 milestone (minor bump), not considering the deployment target drop as needing a major bump as the code itself is backward compatible.

**Pull request merged**
